### ISSUE TITLE
[Feature] Impl `TransactionBuilder::complete_type` for `Optimism`

### ISSUE THREAD

**Issue by emhane** [alloy-rs/op-alloy#27]
### Component

rpc

### Describe the feature you would like

Add type `OpTransactionRequest` that wraps a `TransactionRequest`. Implement method `OpTransactionRequest::complete_deposit`, for using in impl of `TransactionBuilder::complete_type` for `Optimism`.

**Comment by emhane** [comment]
@refcell would you be keen on this?

**Comment by refcell** [comment]
> @refcell would you be keen on this?

Certainly, I'll take a look later today!
