### ISSUE TITLE
[Feature] Rpc type for `optimism_outputAtBlock`

### ISSUE THREAD

**Issue by HrikB** [alloy-rs/op-alloy#32]
### Component

rpc

### Describe the feature you would like

Add a type for the output of `optimism_outputAtBlock` endpoint.

**Comment by refcell** [comment]
> May I?

Certainly - we should be able to effectively copy this `OutputResponse` type https://github.com/paradigmxyz/reth/blob/c788b6a585bbbd7ed92aabc42cb612a6a804daff/crates/optimism/rpc/src/api.rs#L45-L54 over to a new `output` module in the [rpc-types](https://github.com/alloy-rs/op-alloy/blob/main/crates/rpc-types/src/lib.rs) crate

**Comment by martinezjorge** [comment]
Thank you for the reference!
