### ISSUE TITLE
Is this ready for basic use?

### ISSUE THREAD

**Issue by SwayStar123** [alloy-rs/op-alloy#337]
### Component

op-alloy

### Describe the feature you would like

I just want to do eth transfers and erc20 token transfers. is this ready for this basic usage?

### Additional context

Sorry for opening an issue, could not find any other comms

**Comment by mattsse** [comment]
yes, the client side API is mostly the same as for https://github.com/alloy-rs/alloy `Ethereum` network, see also https://github.com/alloy-rs/examples
