### ISSUE TITLE
[Feature] Implement From<TypedTransaction> for OpTypedTransaction

### ISSUE THREAD

**Issue by refcell** [alloy-rs/op-alloy#34]
### Component

consensus, eips, genesis

### Describe the feature you would like

Implement a `From<TypedTransaction> for OpTypedTransaction` where `TypedTransaction` is from anvil.
Place this behind an `anvil` feature flag so that the by-default this impl doesn't add dependency bloat.

### Additional context

This is used for reading anvil transactions into rust test fixtures as in [op-test-vectors](https://github.com/ethereum-optimism/tests/pull/73).

**Comment by mattsse** [comment]
ref https://github.com/foundry-rs/foundry/pull/8595

**Comment by mahmudsudo** [comment]
Hi , can i take on this issue ?
